salt_controllers:
  hosts:
    salt.local:
  vars:
    salt_version: "3007.1"

salt_minions:
  children:
    vault_servers:
    webservers:
  vars:
    salt_version: "3007.1"

vault_servers:
  hosts:
    vault.local:
  vars:
    vault_version: "1.17.3"

webservers:
  hosts:
    nginx.local:
